# run express tests
name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup postgres
        run: docker-compose up .
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test